---
- name: Creating alertmanager user group
  group: name="{{groupId}}"
  become: true
​
- name: Creating alertmanager user
  become: true
  user:
    name: "{{userId}}"
    group: "{{groupId}}"
    system: yes
    shell: "/sbin/nologin"
    comment: "{{userId}} nologin User"
    createhome: no
    state: present
​
- name: Download Alertmanager archive
  get_url:
    url: "https://github.com/prometheus/alertmanager/releases/download/v{{ version }}/alertmanager-{{ version }}.linux-amd64.tar.gz"
    dest: "/home/ubuntu/alertmanager.tar.gz"
    mode: '0644'
​
- name: Unzip Alertmanager archive
  unarchive:
    src: "/home/ubuntu/alertmanager.tar.gz"
    dest: "/home/ubuntu/"
    remote_src: yes
  become: yes
​
- name: Copy alertmanager executable to bin
  become: true
  copy:
    src: "/home/ubuntu/alertmanager-{{ version }}.linux-amd64/alertmanager"
    dest: "/usr/local/bin/alertmanager"
    owner: "{{userId}}"
    group: "{{groupId}}"
    remote_src: yes
    mode: 755
​
- name: Delete alertmanager tmp folder
  file:
    path: "/home/ubuntu/alertmanager-{{ version }}.linux-amd64"
    state: absent
​
- name: Creates data directory
  become: true
  file:
    path: "/data/alertmanager/"
    state: directory
    owner: "{{userId}}"
    group: "{{groupId}}"
    mode: 755
​
- name: Creates config directory
  become: true
  file:
    path: "/etc/alertmanager/"
    state: directory
    owner: "{{userId}}"
    group: "{{groupId}}"
    mode: 755
​
- name: Copy config file
  become: true
  copy:
    src: "templates/alertmanager.j2"
    dest: "/etc/alertmanager/alertmanager.yml"
​
- name: Copy systemd init file
  become: true
  template:
    src: "templates/init.service.j2"
    dest: "/etc/systemd/system/alertmanager.service"
  notify: systemd_reload
​
- name: Start alertmanager service
  become: true
  service:
    name: alertmanager
    state: started
    enabled: yes
