- name: Ensure the required packages are installed
  become: yes
  package:
    name:
      - wget
      - tar
  ignore_errors: yes

- name: Add the 'prometheus' user
  become: yes
  user:
    name: "{{user}}"
    shell: /bin/bash
    create_home: yes
    state: present

- name: Create a directory for Prometheus installation
  become: yes
  file:
    path: /home/prometheus
    owner: "{{user}}"
    group: "{{group}}"
    state: directory

- name: Download Prometheus archive
  become: yes
  get_url:
    url: https://github.com/prometheus/prometheus/releases/download/v{{ version }}/prometheus-{{ version }}.linux-amd64.tar.gz
    dest: /home/prometheus/prometheus-{{ version }}.linux-amd64.tar.gz

- name: Extract Prometheus archive
  become: yes
  ansible.builtin.unarchive:
    src: /home/prometheus/prometheus-{{ version }}.linux-amd64.tar.gz
    dest: /home/prometheus
    remote_src: yes
    creates: /home/prometheus/prometheus-{{ version }}.linux-amd64

- name: create an empty file for prometheus.service
  ansible.builtin.file:
    path: /etc/systemd/system/prometheus.service
    state: touch
    owner: "{{user}}"
    group: "{{group}}"
    mode: 0644


- name: Replace the content of /home/prometheus/prometheus-{{ version }}.linux-amd64/prometheus.yml
  become: yes  
  template:
    src: prometheus_config.j2
    dest: /home/prometheus/prometheus-{{ version }}.linux-amd64/prometheus.yml
    owner: "{{user}}"
    group: "{{group}}"
    mode: 0644

- name: Replace the content of /etc/systemd/system/prometheus.service
  template:
    src: prometheus_service.j2
    dest: /etc/systemd/system/prometheus.service
    owner: root
    group: root
    mode: 0644
  become: true
  notify: systemd_reload
- meta: flush_handlers

- name: Reload systemd to apply changes
  systemd:
    name: "{{user}}"
    state: reloaded
  become: true
