---
- name: Ensure the required packages are installed
  become: yes
  package:
    name:
      - wget
      - tar
  ignore_errors: yes

- name: Add the 'node_exp' user
  become: yes
  user:
    name: "{{user}}"
    shell: /bin/bash
    create_home: yes
    state: present

- name: Create a directory for node_exp installation
  become: yes
  file:
    path: /home/node_exp
    owner: "{{user}}"
    group: "{{group}}"
    state: directory

- name: download node_exporter archive
  become: yes
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v{{ version }}/node_exporter-{{ version }}.linux-amd64.tar.gz
    dest: /home/node_exp/

- name: Extract node_exporter archive
  become: yes
  ansible.builtin.unarchive:
    src: /home/node_exp/node_exporter-{{ version }}.linux-amd64.tar.gz
    dest: /home/node_exp
    remote_src: yes
    creates: /home/node_exp/node_exporter-{{ version }}.linux-amd64

- name: create an empty file for node_exp.services
  become: yes
  ansible.builtin.file:
    path: /etc/systemd/system/node_exp.service
    state: touch
    owner: "{{user}}"
    group: "{{group}}"
    mode: 0644

- name: Replace the content of /etc/systemd/system/node_exp.service
  template:
    src: node_exp.service.j2
    dest: /etc/systemd/system/node_exp.service
    owner: root
    group: root
    mode: 0644
  become: true

- name: Start node_exporter service
  service:
    name: node_exp.service
    state: started
    enabled: yes
  

# - name: Reload systemd
#   become: yes
#   command: systemctl daemon-reload

# - name: command
#   become: yes
#   command: ./node_exporter chdir=/home/node_exp/node_exporter-1.7.0.linux-amd64 &
  
